server:
  port: 8010
spring:
  profiles:
    active: dev
  application:
    name: com.cloud.order
#在配置中心: 可以通过profile进行设置
#只有默认的配置文件才能结合profile进行使用
#对应的Dataid:${spring.application.name}-${profile}.${file-extension:properteis}
#profile的后缀必须跟随默认文件必须配置
managemnet:
  endpoints:
    web:
      exposure:
        include: '*'
#springboot默认的日志级别是info,feign的debug日志级别就不会输入 #全局feign
logging:
  level:
    com.cloud.feign: debug   #com.cloud.feign 这个就是feign接口的包
#feign日志局部配置
feign:
  client:
    config:
      ali-stock:               #对应feign 中name=服务名
        loggerLevel: BASIC
        #contract: feign.Contract.Default #指定Feign原生注解契约配置
        #连接超时时间，默认5s
        connectTimeout: 5000
        #请求处理超时时间,默认3s
        readTimeout: 3000
        #局部feign拦截
        requestInterceptors[0]:
          com.cloud.intercptor.FeignAuthRequestInterceptor