server:
  port: 8010
spring:
  application:
    name: ali-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        enabled: true
        service: ${spring.application.name}
        instance-enabled: true

managemnet:
  endpoints:
    web:
      exposure:
        include: '*'
#springboot默认的日志级别是info,feign的debug日志级别就不会输入 #全局feign
logging:
  level:
    com.cloud.config.FeignConfig: debug
#feign日志局部配置
feign:
  client:
    config:
      ali-order:
        loggerlevel: full
