server:
  port: 8020
spring:
  application:
    name: ali-stock
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.30.62:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public


