server:
  port: 8020
spring:
  application:
    name: ali-stock
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        enabled: true
        service: ${spring.application.name}
        instance-enabled: true
managemnet:
  endpoints:
    web:
      exposure:
        include: '*'


